### ISSUE TITLE
rundeck not sending args correctly

### ISSUE THREAD

**Issue by jaredstehler** [rerun-modules/rundeck-plugin#3]
I can't seem to get the `waitfor:http` plugin to work in rundeck, it keeps erroring out with:

```
[error] waitfor:http: usage: rerun waitfor:http  --url <> 
```

I'm seeing this on the latest rundeck (v2.6.6-1), and with the latest build of waitfor.

Here's the relevant bit from my job config:

``` yaml
    - configuration:
        interval: '30'
        url: https://foo.com/deploy/v1/health
      description: Wait for deploy service to become healthy
      nodeStep: true
      type: waitfor:http
```
